#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Author: Yuki Furuta <furushchev@jsk.imi.i.u-tokyo.ac.jp>

import os
from StringIO import StringIO
from urdf_parser_py.urdf import URDF
import tf.transformations as T
import numpy as np

from utils import UniqueStringGenerator
from gazebo import resolve_model_path


class URDF2SEM(object):
    def __init__(self, urdf_path, sem_path):
        self.nsmap = {
            "xsd": "http://www.w3.org/2001/XMLSchema#",
            "owl": "http://www.w3.org/2002/07/owl#",
            "xsd": "http://www.w3.org/2001/XMLSchema#",
            "srdl2": "http://knowrob.org/kb/srdl2.owl#",
            "owl2xml": "http://www.w3.org/2006/12/owl2-xml#",
            "knowrob": "http://knowrob.org/kb/knowrob.owl#",
            "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
            "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
            "srdl2-comp": "http://knowrob.org/kb/srdl2-comp.owl#",
            "srdl2-cap": "http://knowrob.org/kb/srdl2-cap.owl#",
            "qudt-unit": "http://qudt.org/vocab/unit#",
        }
        self.imports = [
            "package://knowrob_srdl/owl/srdl2-comp.owl",
            "package://knowrob_common/owl/knowrob.owl",
        ]
        self.id_gen = UniqueStringGenerator()
        self.urdf = URDF.from_xml_file(urdf_path)
        self.urdf.check_valid()

        basename = os.path.basename(sem_path)
        namespace, _ = os.path.splitext(basename)
        self.map_ns = namespace
        self.map_name = self.urdf.name + "_" + self.id_gen.gen()
        self.map_uri_base = "http://knowrob.org/kb/%s" % basename
        self.map_uri = self.map_uri_base + "#"
        self.nsmap[self.map_ns] = self.map_uri
        self.transformations = {}

    def to_string(self):
        s = StringIO()
        self.write_header(s)
        self.write_imports(s)
        self.write_instance(s)
        self.write_links(s)
        self.write_joints(s)
        self.write_footer(s)

        return s.getvalue()

    def write_header(self, s):
        s.write("""\
<?xml version="1.0"?>

<!-- =============================================== -->
<!-- | This file was autogenerated by URDF2SEM     | -->
<!-- =============================================== -->\n""")

        # write doctype
        s.write("""\n<!DOCTYPE rdf:RDF [\n""")
        for name, uri in self.nsmap.items():
            s.write("""<!ENTITY {name} "{uri}">\n""".format(**locals()))
        s.write("""]>\n\n""")

        # write rdf:RDF tag begin
        s.write("""<rdf:RDF xml:base="%s"\n""" % self.map_uri_base)
        s.write("""         xmlns="%s\"""" % self.map_uri)
        for name, uri in self.nsmap.items():
            s.write("""\n         xmlns:{name}="{uri}\"""".format(**locals()))
        s.write(""">\n""")

    def write_footer(self, s):
        s.write("""\n</rdf:RDF>\n""")

    def write_imports(self, s):
        s.write("""
    <!-- =========================================== -->
    <!-- |   Ontology Imports                      | -->
    <!-- =========================================== -->

""")
        s.write("""    <owl:Ontology rdf:about="{map_uri_base}">\n""".format(map_uri_base=self.map_uri_base))
        for imp in self.imports:
            s.write("""      <owl:imports rdf:resource="{imp}"/>\n""".format(imp=imp))
        s.write("""    </owl:Ontology>\n""")
        return s.getvalue()

    def write_instance(self, s):
        s.write("""
    <!-- =========================================== -->
    <!-- |   Semantic Environment Map Instance     | -->
    <!-- =========================================== -->

    <owl:NamedIndividual rdf:about="&{map_ns};{map_name}">
        <rdf:type rdf:resource="&knowrob;SemanticEnvironmentMap"/>
    </owl:NamedIndividual>

    <owl:NamedIndividual rdf:about="&{map_ns};timepoint_0000000001">
        <rdf:type rdf:resource="&knowrob;TimePoint"/>
    </owl:NamedIndividual>\n""".format(map_ns=self.map_ns, map_name=self.map_name))

    def write_link(self, s, link_name):
        map_ns = self.map_ns
        map_name = self.map_name
        prefix = self.map_name + "_"
        link = self.urdf.link_map[link_name]

        mesh_file_name = None
        mesh_scale = None
        if link.visual is not None:
            mesh_file_name = resolve_model_path(link.visual.geometry.filename)
            mesh_scale = "%f %f %f" % tuple(link.visual.geometry.scale)

        s.write("""
    <owl:NamedIndividual rdf:about="&{map_ns};{prefix}{link_name}">
        <rdf:type rdf:resource="&srdl2-comp;UrdfLink"/>
        <srdl2-comp:urdfName>{link_name}</srdl2-comp:urdfName>
        <knowrob:describedInMap rdf:resource="&{map_ns};{map_name}"/>""".format(**locals()))
        if link_name in self.urdf.child_map:
            for joint_name, _ in self.urdf.child_map[link_name]:
                s.write("""
        <srdl2-comp:succeedingJoint rdf:resource="&{map_ns};{prefix}{joint_name}"/>""".format(**locals()))
        if mesh_file_name is None:
            s.write("""
        <knowrob:hasVisual rdf:datatype="&xsd;boolean">false</knowrob:hasVisual>""")
        else:
            s.write("""
        <knowrob:pathToCadModel rdf:datatype="&xsd;string">{mesh_file_name}</knowrob:pathToCadModel>""".format(**locals()))
        if mesh_scale is not None:
            s.write("""
        <srdl2-comp:mesh_scale rdf:datatype="&xsd;string">{mesh_scale}</srdl2-comp:mesh_scale>""".format(**locals()))
        s.write("""
    </owl:NamedIndividual>\n""")

    def write_transformation(self, s, link_name, absolute=True):
        prefix = self.map_name + "_"
        try:
            parent_joint_name = self.urdf.parent_map[link_name][0]
            joint = self.urdf.joint_map[parent_joint_name]
        except: return
        map_ns = self.map_ns
        perception_name = "SemanticMapPerception_" + self.id_gen.gen()
        transformation_name = "Transformation_" + self.id_gen.gen()

        # write perception
        s.write("""
    <owl:NamedIndividual rdf:about="&{map_ns};{perception_name}">
        <rdf:type rdf:resource="&knowrob;SemanticMapPerception"/>
        <knowrob:eventOccursAt rdf:resource="&{map_ns};{transformation_name}"/>
        <knowrob:startTime rdf:resource="&{map_ns};timepoint_0000000001"/>
        <knowrob:objectActedOn rdf:resource="&{map_ns};{prefix}{link_name}"/>
    </owl:NamedIndividual>""".format(**locals()))

        # write transformation
        s.write("""
    <owl:NamedIndividual rdf:about="&{map_ns};{transformation_name}">
        <rdf:type rdf:resource="&knowrob;Transformation"/>""".format(**locals()))
        translation = "0.0 0.0 0.0"
        quaternion = "0.0 0.0 0.0 1.0"
        if absolute:
            t, q = self.calc_transformation_from_root_link(link_name)
            translation = "%f %f %f" % t
            quaternion = "%f %f %f %f" % q
        else:
            # relative to parent transformation
            if joint.parent in self.transformations:
                parent_transformation_name = self.transformations[joint.parent]
                s.write("""
        <knowrob:relativeTo rdf:resource="&{map_ns};{parent_transformation_name}"/>""".format(**locals()))
            if joint.origin is not None:
                translation = "%f %f %f" % tuple(joint.origin.xyz)
                q = T.quaternion_from_euler(*joint.origin.rpy)
                quaternion = "%f %f %f %f" % (q[3], q[0], q[1], q[2])
        s.write("""
        <knowrob:translation rdf:datatype="&xsd;string">{translation}</knowrob:translation>
        <knowrob:quaternion rdf:datatype="&xsd;string">{quaternion}</knowrob:quaternion>
    </owl:NamedIndividual>\n""".format(**locals()))
        self.transformations[link_name] = transformation_name

    def calc_transformation_from_root_link(self, link_name):
        joint_names = self.urdf.get_chain(self.urdf.get_root(), link_name,
                                          joints=True, links=False)
        joints = [self.urdf.joint_map[j] for j in joint_names]
        m = np.dot(T.translation_matrix((0,0,0)),
                   T.euler_matrix(0,0,0))
        for j in joints:
            if j.origin is None:
                continue
            n = np.dot(T.translation_matrix(tuple(j.origin.xyz)),
                       T.euler_matrix(*tuple(j.origin.rpy)))
            m = np.dot(m, n)
        t = T.translation_from_matrix(m)
        q = T.quaternion_from_matrix(m)
        return tuple(t), (q[3], q[0], q[1], q[2])

    def write_link_recursive(self, s, link_name):
        self.write_link(s, link_name)
        self.write_transformation(s, link_name)
        if link_name in self.urdf.child_map:
            for j, child_link in self.urdf.child_map[link_name]:
                self.write_link_recursive(s, child_link)

    def write_links(self, s):
        s.write("""
    <!-- =========================================== -->
    <!-- |   Robot Links                           | -->
    <!-- =========================================== -->""")
        s.write("\n\n")

        # link definition
        self.write_link_recursive(s, self.urdf.get_root())

    def write_joints(s, joint_name):
        pass
