#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Author: Yuki Furuta <furushchev@jsk.imi.i.u-tokyo.ac.jp>


import argparse
import sys

import knowrob_semantic_maps


def execute(args):
    if knowrob_semantic_maps.urdf_to_sem(args.urdf, args.sem, args.overwrite):
        return 0
    else:
        return 1

if __name__ == '__main__':
    parser = argparse.ArgumentParser()

    parser.add_argument("urdf", type=str,
                        help="Path to URDF file")
    parser.add_argument("sem", type=str, default=None, nargs='?',
                        help="Path to output SemanticEnvironmentMap file")

    parser.add_argument("-n", "--namespace", type=str,
                        help="Namespace of output map")
    parser.add_argument("-f", "--overwrite", action='store_true', default=False,
                        help="Overwrite output file if exists")

    args = parser.parse_args()

    sys.exit(execute(args))
